(()=>{const sleep=t=>new Promise(z=>setTimeout(z,t));
window.__leaf=t=>[...document.querySelectorAll('*')].filter(e=>e.childElementCount==0&&e.textContent.trim()==t&&e.getBoundingClientRect().width>0);
window.__clickT=t=>{const e=__leaf(t)[0];if(!e)return false;(e.closest('button,[role=button],[role=tab],label')||e).click();return true};
window.__byPath=p=>{const L=[...document.querySelectorAll('button')].filter(b=>(b.querySelector('svg path')?.getAttribute('d')||'').startsWith(p)&&b.getBoundingClientRect().width>0);return L.find(b=>{const r=b.getBoundingClientRect();return r.x>=0&&r.x<innerWidth&&r.y>=0&&r.y<innerHeight})||L[0]};
window.__back=async()=>{const b=[...document.querySelectorAll('button')].find(b=>b.querySelector('svg path')?.getAttribute('d')?.startsWith('M15 6l-6 6l6 6')&&b.getBoundingClientRect().y<200&&b.getBoundingClientRect().width>0);if(b){b.click();await sleep(1500);return true}return false};
window.__page=async dir=>{const p=dir>0?'M9 6l6 6l-6 6':'M15 6l-6 6l6 6';const b=[...document.querySelectorAll('button')].find(b=>{const r=b.getBoundingClientRect();return b.querySelector('svg path')?.getAttribute('d')?.startsWith(p)&&r.y>600&&r.x>150&&r.x<450&&r.width>0});if(b&&!b.disabled){b.click();await sleep(1800);return true}return false};
window.__assets=async()=>{if(!__leaf('Search my generation').length){__clickT('Assets');await sleep(1500)}await __back();const lv=[...document.querySelectorAll('button')].find(b=>(b.querySelector('svg path')?.getAttribute('d')||'').startsWith('M4 6l16 0')&&b.getBoundingClientRect().y>600&&!b.disabled);const hasGroups=[...document.querySelectorAll('button')].some(b=>b.querySelector('svg path')?.getAttribute('d')?.startsWith('M9 6l6 6l-6 6')&&b.getBoundingClientRect().x>500&&b.getBoundingClientRect().width>0);if(lv&&!hasGroups){lv.click();await sleep(1500)}};
window.__isChev=b=>b.tagName=='BUTTON'&&(b.querySelector('svg path')?.getAttribute('d')||'').startsWith('M9 6l6 6l-6 6')&&b.getBoundingClientRect().x>500;
window.__grp=name=>{const g=__leaf(name)[0];if(!g)return null;let c=g;for(let k=0;k<8&&c;k++){c=c.parentElement;if([...c.querySelectorAll('button')].some(__isChev))return c.parentElement}return null};
window.__scroller=()=>{const ch=[...document.querySelectorAll('button')].find(b=>__isChev(b));let e=ch;while(e&&e!==document.body){e=e.parentElement;const cs=getComputedStyle(e);if(/(auto|scroll)/.test(cs.overflowY)&&e.scrollHeight>e.clientHeight+20)return e}return null};
window.__list=async()=>{await sleep(1000);const seen=new Map();const sc=__scroller();for(let s=0;s<30;s++){[...document.querySelectorAll('button')].filter(b=>__isChev(b)).forEach(b=>{const name=b.parentElement.innerText.trim().split('\n')[0];if(!name)return;const g=b.parentElement.parentElement;seen.set(name+'#'+Math.round(b.getBoundingClientRect().y+(sc?sc.scrollTop:0)),name+' | v'+g.querySelectorAll('img').length+' '+(g.innerText.match(/\d+%/g)||[]).join('/'))});if(!sc)break;const before=sc.scrollTop;sc.scrollTop+=400;await sleep(350);if(sc.scrollTop==before)break}if(sc)sc.scrollTop=0;return [...seen.values()].join('\n')};
window.__find=async name=>{await __assets();const look=async()=>{const sc=__scroller();if(sc)sc.scrollTop=0;await sleep(300);for(let s=0;s<30;s++){if(__leaf(name).length){__leaf(name)[0].scrollIntoView({block:'center'});await sleep(500);return true}if(!sc)break;const b=sc.scrollTop;sc.scrollTop+=400;await sleep(350);if(sc.scrollTop==b)break}return false};while(await __page(-1)){}for(let p=0;p<6;p++){if(await look())return true;if(!(await __page(1)))break}return false};
window.__all=async()=>{await __assets();while(await __page(-1)){}const out=[];for(let p=0;p<4;p++){out.push(await __list());if(!(await __page(1)))break}while(await __page(-1)){}return out.join('\n')};
window.__prep=async name=>{if(!(await __find(name)))return 'not found '+name;const c=__grp(name);const n=c.querySelectorAll('img').length;c.querySelectorAll('img')[0].click();await sleep(2800);for(let t=0;t<3&&!__leaf('Target Polycount').length;t++){__byPath('m9.13 8 4.74')?.click();await sleep(900)}return (__leaf('Target Polycount').length?'ready ':'NOT OPEN ')+name+' (versions '+n+')'};
window.__dl=async()=>{const sl=t=>new Promise(z=>setTimeout(z,t));const vis=()=>[...document.querySelectorAll('button')].filter(x=>{if(x.innerText.trim()!='Download'||x.disabled||x.getBoundingClientRect().width==0)return false;let p=x;for(let k=0;k<6&&p;k++){p=p.parentElement;if(p&&/Download Settings/.test(p.innerText))return true}return false});const b=__byPath('M4.933 6.272');if(!b)return 'no dl btn';if(!vis().length){b.click()}for(let t=0;t<12;t++){await sl(700);const d=vis().pop();if(d){await sl(400);d.click();await sl(1500);if(vis().length){b.click();await sl(600)}return 'download clicked'+(vis().length?' (popup still open)':'')}}return 'no download'};
window.__pst=()=>['Custom','3K','10K','30K','100K'].map(t=>{const e=__leaf(t)[0];if(!e)return '';const b=e.closest('button,[role=radio],[role=tab],div');return (b.getAttribute('data-state')||b.getAttribute('aria-checked'))=='checked'?t:''}).join('');
window.__got=window.__got||new Set();
window.__get=async name=>{if(__got.has(name))return name+': already have';if(!(await __find(name)))return name+': not found';const c=__grp(name);if(/\d+%/.test(c.innerText))return name+': still working';const n=c.querySelectorAll('img').length;if(n<3)return name+': not remeshed yet (v'+n+')';c.querySelectorAll('img')[0].click();await sleep(3000);const r=await __dl();await sleep(2500);__clickT('Assets');await sleep(1200);if(/clicked/.test(r))__got.add(name);return name+' (v'+n+'): '+r};
window.__shrink=async(ab,size)=>{size=size||1024;const dv=new DataView(ab);let off=12,J=null,BIN=null;while(off<ab.byteLength){const len=dv.getUint32(off,true),typ=dv.getUint32(off+4,true);const d=ab.slice(off+8,off+8+len);if(typ==0x4E4F534A)J=JSON.parse(new TextDecoder().decode(d));else if(typ==0x004E4942)BIN=d;off+=8+len}
const base=new Set();(J.materials||[]).forEach(m=>{const t=m.pbrMetallicRoughness&&m.pbrMetallicRoughness.baseColorTexture;if(t)base.add(J.textures[t.index].source)});
const enc=async(blob,s,q)=>{const bm=await createImageBitmap(blob);const c=new OffscreenCanvas(s,s);c.getContext('2d').drawImage(bm,0,0,s,s);return new Uint8Array(await (await c.convertToBlob({type:'image/jpeg',quality:q})).arrayBuffer())};
const nd={};for(let i=0;i<(J.images||[]).length;i++){const im=J.images[i];if(im.bufferView==null)continue;const bv=J.bufferViews[im.bufferView];const src=new Blob([new Uint8Array(BIN,bv.byteOffset||0,bv.byteLength)],{type:im.mimeType||'image/png'});nd[im.bufferView]=base.has(i)?await enc(src,size,.9):await enc(src,4,.5);im.mimeType='image/jpeg'}
const parts=[];let pos=0;J.bufferViews.forEach((bv,k)=>{const data=nd[k]||new Uint8Array(BIN,bv.byteOffset||0,bv.byteLength);const pad=(4-(pos%4))%4;if(pad){parts.push(new Uint8Array(pad));pos+=pad}bv.byteOffset=pos;bv.byteLength=data.byteLength;parts.push(data);pos+=data.byteLength});const p2=(4-(pos%4))%4;if(p2){parts.push(new Uint8Array(p2));pos+=p2}J.buffers[0].byteLength=pos;
const js=new TextEncoder().encode(JSON.stringify(J));const jp=(4-(js.length%4))%4;const jsb=new Uint8Array(js.length+jp).fill(32);jsb.set(js);const h=new DataView(new ArrayBuffer(20));h.setUint32(0,0x46546C67,true);h.setUint32(4,2,true);h.setUint32(8,12+8+jsb.length+8+pos,true);h.setUint32(12,jsb.length,true);h.setUint32(16,0x4E4F534A,true);const h2=new DataView(new ArrayBuffer(8));h2.setUint32(0,pos,true);h2.setUint32(4,0x004E4942,true);return new Blob([h.buffer,jsb,h2.buffer,...parts],{type:'model/gltf-binary'})};
window.__slog=window.__slog||[];
if(!window.__hook){window.__hook=1;const oc=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){const href=this.href,name=this.download||'';if(/\.glb/i.test(name+href)&&!/^blob:/.test(href)){(async()=>{let res;for(let t=0;t<3;t++){try{const ab=await fetch(href,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('status '+r.status);return r.arrayBuffer()});const sm=await __shrink(ab);const a=document.createElement('a');a.href=URL.createObjectURL(sm);a.download='small_'+name.replace(/^Meshy_AI_/,'').replace(/\s+/g,'_');document.body.appendChild(a);oc.call(a);a.remove();res=[name,ab.byteLength,sm.size];break}catch(e){res=[name,'ERR '+e.message];await sleep(4000)}}__slog.push(res)})();return}return oc.call(this)}}
const BASE='https://raw.githubusercontent.com/Mrsnakehunter/Memecapes/art-staging/meshy/';
const sw=()=>[...document.querySelectorAll('[role=switch]')];const swBy=lab=>sw().find(s=>{let p=s;for(let k=0;k<5&&p;k++){p=p.parentElement;if(p&&p.innerText&&p.innerText.trim().split('\n')[0].trim()==lab)return true}return false});const ins=()=>[...document.querySelectorAll('input[type=file]')];
const put=async(inp,file)=>{const b=await fetch(BASE+file+'?'+Date.now()).then(r=>{if(!r.ok)throw new Error('missing '+file);return r.blob()});const dt=new DataTransfer();dt.items.add(new File([b],file,{type:'image/png'}));inp.files=dt.files;inp.dispatchEvent(new Event('change',{bubbles:true}));await sleep(2300)};
const settings=async()=>{const std=[...document.querySelectorAll('button,div,span')].find(e=>e.childElementCount==0&&e.textContent.trim()=='Standard');if(std){std.click();await sleep(400)}const tx=swBy('Texture');if(tx&&tx.getAttribute('aria-checked')!='true'){tx.click();await sleep(400)}const ps=swBy('Pose');if(ps&&ps.getAttribute('aria-checked')=='true'){ps.click();await sleep(300)}};
const go=()=>{const g=[...document.querySelectorAll('button')].find(b=>b.innerText.trim()=='Generate'&&b.getBoundingClientRect().y>600);g.click()};
window.__gen=async(n)=>{__clickT('Toolkit');await sleep(1500);await put(ins()[0],n+'_front.png');const mv=swBy('Multi-view');if(mv&&mv.getAttribute('aria-checked')!='true'){mv.click();await sleep(800)}for(const [lab,v] of [['Left','left'],['Back','back'],['Right','right']]){const i=ins().find(i=>i.parentElement.innerText.trim()==lab);if(!i)return n+': no slot '+lab;await put(i,n+'_'+v+'.png')}await settings();go();return n+': GENERATED 4-view'};
window.__genP=async(file)=>{__clickT('Toolkit');await sleep(1500);const mv=swBy('Multi-view');if(mv&&mv.getAttribute('aria-checked')=='true'){mv.click();await sleep(800)}await put(ins()[0],file);await settings();go();return file+': GENERATED single'};
window.__runlog=[];window.__run=list=>{(async()=>{for(const [n,k] of list){try{__runlog.push(k=='p'?await __genP(n):await __gen(n))}catch(e){__runlog.push(n+' ERR '+e)}await sleep(6000)}__runlog.push('DONE')})()};
window.__dlog=[];window.__getAll=list=>{(async()=>{for(const n of list){try{__dlog.push(await __get(n))}catch(e){__dlog.push(n+' ERR '+e)}await sleep(1500)}__dlog.push('DONE')})()};
return 'helpers ready'})()
